require('dotenv').config();
const mongoose = require('mongoose');
const crypto = require('crypto');
const bcrypt = require('bcrypt');
const User = require('./models/User');
const Message = require('./models/Message');
const AdminConfig = require('./models/AdminConfig');
const { hashPassword } = require('./crypto');
const connectDB = require('./config/db');

// This script simulates what would normally happen securely on the client side
// (generating RSA keys for users and admin, generating PBKDF2 derived keys from passwords).

// 1. PBKDF2 configuration
const MASTER_KEY = '1234567890123456';
const ALGORITHM = 'aes-256-gcm';

const deriveKey = (password, saltBuffer) => {
  return crypto.pbkdf2Sync(password, saltBuffer, 100000, 32, 'sha256');
};

const encryptWithAES = (text, keyBuffer) => {
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv(ALGORITHM, keyBuffer, iv);
  let encrypted = cipher.update(text, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  const authTag = cipher.getAuthTag().toString('hex');
  return { encrypted, iv: iv.toString('hex'), authTag };
};

const generateRSAKeyPair = () => {
  return crypto.generateKeyPairSync('rsa', {
    modulusLength: 2048,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });
};

const seed = async () => {
  await connectDB();

  console.log('Clearing old data...');
  await User.deleteMany();
  await Message.deleteMany();
  await AdminConfig.deleteMany();

  console.log('Generating Admin Setup...');
  const adminKeys = generateRSAKeyPair();
  const adminMasterHash = await hashPassword(MASTER_KEY);
  
  const salt = crypto.randomBytes(16);
  const derivedKey = deriveKey(MASTER_KEY, salt);
  const encryptedAdminPrivateKeyPayload = encryptWithAES(adminKeys.privateKey, derivedKey);
  
  // Combine encrypted data for easy storage (IV + AuthTag + Ciphertext)
  const encryptedPrivKeyCombined = JSON.stringify(encryptedAdminPrivateKeyPayload);

  await AdminConfig.create({
    username: 'admin',
    password_hash: adminMasterHash,
    admin_public_key: adminKeys.publicKey,
    encrypted_admin_private_key: encryptedPrivKeyCombined,
    salt: salt.toString('hex')
  });

  console.log('Admin seeded.');

  console.log('Generating Users...');
  
  const user1Keys = generateRSAKeyPair();
  const user1Hash = await hashPassword('password123');
  const user1 = await User.create({
    email: 'user1@test.com',
    password_hash: user1Hash,
    public_key: user1Keys.publicKey
  });

  const user2Keys = generateRSAKeyPair();
  const user2Hash = await hashPassword('password123');
  const user2 = await User.create({
    email: 'user2@test.com',
    password_hash: user2Hash,
    public_key: user2Keys.publicKey
  });

  console.log('Users seeded.');
  console.log('\n--- IMPORTANT: SIMULATED SECURE STORAGE (CLIENT-SIDE) ---');
  console.log('In a real environment, private keys are generated by the device, never touch the server, and are stored in SecureStore.');
  console.log('\nUSER 1 PRIVATE KEY:\n', user1Keys.privateKey);
  console.log('\nUSER 2 PRIVATE KEY:\n', user2Keys.privateKey);
  console.log('\n---------------------------------------------------------');

  process.exit();
};

seed();
